### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by rpeshkov** [vscode-org-mode/vscode-org-mode-fork#3]
Currently there are no tests available at all. This is really bad, since it's not possible to catch regressions during development.

From my point of view it's better to start with e2e tests that will be checking functionality from the user perspective. It will give an option to change internal structure of the extension without worrying for broken functionality.

Here's the list of commands of the extension, for each of those a test need to be implemented, creating initial document, invoking command and comparing with expected result:

- [x] org.insertHeadingRespectContent
- [x] org.insertSubheading
- [x] org.doDemote
- [x] org.doPromote
- [x] org.promoteSubtree
- [x] org.demoteSubtree
- [x] org.timestamp
- [ ] org.clockin
- [ ] org.clockout
- [ ] org.updateclock
- [x] org.incrementContext
- [x] org.decrementContext
- [x] org.bold
- [x] org.italic
- [x] org.underline
- [x] org.code
- [x] org.verbose
- [x] org.literal
- [ ] org.butterfly

**Comment by rpeshkov** [comment]
@sipi, @aboukirev, @AdrieanKhisbe and everyone else. I have a question: some functions are working incorrectly, compared to emacs org behaviour. Should such functions be covered with tests and what kind of tests should it be: test that checks current functionality, that's incorrect (and will be passing) or it should check how it should be (and will be failing)?

**Comment by AdrieanKhisbe** [comment]
I personally favor adding the test checkying the Org behavior. 
We'll fix them in another PR before making a release.

**Comment by sipi** [comment]
I'm in favour of the emacs org behaviour.

**Comment by sipi** [comment]
What about butterflies ?
https://www.xkcd.com/378/

**Comment by AdrieanKhisbe** [comment]
🐛

**Comment by rpeshkov** [comment]
@sipi, @AdrieanKhisbe, maybe it's better to go another way with tests? Since for every command I check how it works (not in details, but still...), maybe it will be reasonable not to add test for buggy command, but raise an issue for fixing it and add test in scope of that issue?

**Comment by aboukirev** [comment]
Tests are code.  I think, an issue should describe inconsistent behavior
and, perhaps, suggest a test.
The fix will include the test that failed in the original version and
passes in the fixed version.  A test is a convenient way to work on a fix
and to ensure the issue does not return.

Alexei Boukirev
