### ISSUE TITLE
Demote/Promote Subtree must affect only child elements

### ISSUE THREAD

**Issue by rpeshkov** [vscode-org-mode/vscode-org-mode-fork#9]
'Demote Subtree' and 'Promote Subtree' commands currently affect not only child elements, but elements on the same level as well.

Example document:

```
* Header
** SubHeader

* Header 2
```

Current behavior after 'Demote Subtree':

```
** Header
*** SubHeader

** Header 2
```

Expected behavior after 'Demote Subtree':

```
** Header
*** SubHeader

* Header 2
```

Notice difference in 'Header 2' header level.

The same issue valid for 'Promote Subtree' command.

**Comment by sipi** [comment]
I does not use these commands, but I tested and I reproduced this bug.
